/// Artimech
/// 
/// Copyright © <2017> <George A Lancaster>
/// Permission is hereby granted, free of charge, to any person obtaining a copy of this software 
/// and associated documentation files (the "Software"), to deal in the Software without restriction, 
/// including without limitation the rights to use, copy, modify, merge, publish, distribute, 
/// sublicense, and/or sell copies of the Software, and to permit persons to whom the Software 
/// is furnished to do so, subject to the following conditions:
/// The above copyright notice and this permission notice shall be included in all copies 
/// or substantial portions of the Software.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
/// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS 
/// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
/// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
/// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
/// OTHER DEALINGS IN THE SOFTWARE.

using UnityEngine;
using System.Collections;
using UnityEngine.UI;

namespace Artimech
{
    public class aMechGmSymbolButton : stateMachineGame
    {
        [Header("Symbol Tuning Config:")]

        [SerializeField]
        [Tooltip("Fade the color in curve.")]
        AnimationCurve m_FadeInCurve;
        [SerializeField]
        [Tooltip("Fade the color out curve.")]
        AnimationCurve m_FadeOutCurve;

        [SerializeField]
        [Tooltip("How long to wait till the intro message gets faded out after fade in starts.")]
        AudioSource m_SymbolSound;
        [SerializeField]
        [Tooltip("How long to wait till the intro message gets faded out after fade in starts.")]
        float m_SymbolSoundPitchChange = 1.0f;

        [SerializeField]
        [Tooltip("Error Color")]
        Color m_ErrorColor;


        Color m_StartColor;
        Color m_ImageStartColor;
        Color m_PulseColor;
        bool m_PulseColorBool;

        public bool PulseColorBool { get => m_PulseColorBool; set => m_PulseColorBool = value; }
        public AnimationCurve FadeOutCurve { get => m_FadeOutCurve; }
        public AnimationCurve FadeInCurve { get => m_FadeInCurve; }
        public Color StartColor { get => m_StartColor; set => m_StartColor = value; }
        public Color PulseColor { get => m_PulseColor; }
        public Color ImageStartColor { get => m_ImageStartColor; }
        public AudioSource SymbolSound { get => m_SymbolSound; set => m_SymbolSound = value; }
        public float SymbolSoundPitchChange { get => m_SymbolSoundPitchChange;}

        public void SetPulseColor(Color colorToPulse) { m_PulseColor = colorToPulse; PulseColorBool = true; }

        new void Awake()
        {
            base.Awake();
            CreateStates();
        }

        // Use this for initialization
        new void Start()
        {
            StartColor = gameObject.GetComponent<Button>().colors.normalColor;
            m_ImageStartColor = gameObject.GetComponent<Image>().color;
            base.Start();
        }

        // Update is called once per frame
        new void Update()
        {
            base.Update();
        }

        new void FixedUpdate()
        {
            base.FixedUpdate();
        }

        /// <summary>
        /// Autogenerated state are created here inside this function.
        /// </summary>
        void CreateStates()
        {

            m_CurrentState = AddState(new gmSymbolInit(this.gameObject), "gmSymbolInit");

            //<ArtiMechStates>
            AddState(new gmSymbolErrorStrobe(this.gameObject), "gmSymbolErrorStrobe");
            AddState(new gmSymbolError(this.gameObject), "gmSymbolError");
            AddState(new gmSymbolFadeDownColor(this.gameObject), "gmSymbolFadeDownColor");
            AddState(new gmSymbolFadeUpColor(this.gameObject), "gmSymbolFadeUpColor");
            AddState(new gmSymbolUpdate(this.gameObject), "gmSymbolUpdate");

        }
    }
}