/// Artimech
/// 
/// Copyright © <2017> <George A Lancaster>
/// Permission is hereby granted, free of charge, to any person obtaining a copy of this software 
/// and associated documentation files (the "Software"), to deal in the Software without restriction, 
/// including without limitation the rights to use, copy, modify, merge, publish, distribute, 
/// sublicense, and/or sell copies of the Software, and to permit persons to whom the Software 
/// is furnished to do so, subject to the following conditions:
/// The above copyright notice and this permission notice shall be included in all copies 
/// or substantial portions of the Software.
/// 
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
/// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS 
/// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
/// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
/// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
/// OTHER DEALINGS IN THE SOFTWARE.

using UnityEngine;
using System.Collections;
using UnityEngine.UI;

namespace Artimech
{
    public class aMechGmController : stateMachineGame
    {
        [Header("aMechGmController:")]
        [SerializeField]
        [Tooltip("0 is mid, 1 is left and 2 is right")]
        Button[] m_Buttons;
        [SerializeField]
        [Tooltip("Puzzel Colors")]
        Color[] m_PuzzelColors;
        [SerializeField]
        [Tooltip("Puzzel Colors")]
        Color m_ErrorColor;

        bool m_AllButtonsOff = false;

        public Button[] Buttons { get => m_Buttons; set => m_Buttons = value; }
        public bool AllButtonsOff { get => m_AllButtonsOff; set => m_AllButtonsOff = value; }

        new void Awake()
        {
            base.Awake();
            CreateStates();
        }

        // Use this for initialization
        new void Start()
        {
            base.Start();
        }

        // Update is called once per frame
        new void Update()
        {
            base.Update();
        }

        new void FixedUpdate()
        {
            base.FixedUpdate();
        }

        /// <summary>
        /// Autogenerated state are created here inside this function.
        /// </summary>
        void CreateStates()
        {

            m_CurrentState = AddState(new gmControllerInit(this.gameObject), "gmControllerInit");

            //<ArtiMechStates>
            AddState(new gmTurnOffAllButtonInput(this.gameObject),"gmTurnOffAllButtonInput");
            AddState(new gmControllerTurnOffSideButtonInput(this.gameObject),"gmControllerTurnOffSideButtonInput");
            AddState(new gmControllerSuccessInput(this.gameObject),"gmControllerSuccessInput");
            AddState(new gmControllerFailedInput(this.gameObject),"gmControllerFailedInput");
            AddState(new gmControllerWaitSymbolInput(this.gameObject),"gmControllerWaitSymbolInput");
            AddState(new gmControllerAddSymbol(this.gameObject),"gmControllerAddSymbol");
            AddState(new gmControllerPlayBackSymbols(this.gameObject),"gmControllerPlayBackSymbols");
            AddState(new gmControllerWait(this.gameObject),"gmControllerWait");

        }
    }
}
